import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ChakraProvider } from '@chakra-ui/react';
import dynamic from 'next/dynamic';

const StaticAuthentication = dynamic(() => import('@/components/StaticAuthentication'), { ssr: false });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Rick and Morty on Next.js + Chakra UI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ChakraProvider>
          <main>
            <StaticAuthentication>{children}</StaticAuthentication>
          </main>
        </ChakraProvider>
      </body>
    </html>
  );
}
